# Generated by Django 3.2.3 on 2021-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readCsv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='No_Boys_Appeared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='No_Boys_Passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='No_Girls_Appeared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='No_Girls_Passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='No_Total_Passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='Total_Appeared',
            field=models.IntegerField(default=0),
        ),
    ]
