# Generated by Django 3.2.3 on 2021-06-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readCsv', '0003_auto_20210623_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
